mission_title: Missão 
mission_value: Fornecer produtos de bens de consumo com foco na distribuição numérica promovendo o crescimento do mercado varejista.
vision_title: Visão
vision_value: Tornar-se a melhor e mais eficiente distribuidora do estado do Rio Grande do Norte sem comprometer a qualidade de distribuição nos próximos 5 anos.
values_title: Valores
values_value1: Compromisso
values_value2: Rapidez
values_value3: Confiança
values_value4: Parceria
values_value5: União